### ISSUE TITLE
上传文件,然后嗝屁.

### ISSUE THREAD

**Issue by shirakun** [J3n5en/sinaPicHostingApi#1]
(node:13886) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property '1' of null
(node:13886) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
cookies.json空的
微博账户新注册的
启动时不报错,向api提交文件才出错
dalao快修复啊

**Comment by J3n5en** [comment]
我这边还没出现这种情况.你可以检查一下新浪是否登录成功了,或者把cookie.json这个文件删了重新登录试试

**Comment by shirakun** [comment]
会不会是登录需要验证码的问题啊

**Comment by shirakun** [comment]
检查了cooki.json是空的,然后我微博账户新注册的,登录需要验证码,应该是验证码的问题了

**Comment by shirakun** [comment]
cookie.json里存的是标准的json吗,我用php把cookie序列化之后保存进去启动的时候直接报错诶

**Comment by J3n5en** [comment]
提供一个临时的解决方案
同目录下创建一个`string2jar.js`

```
const tough = require('tough-cookie')
const FileCookieStore = require("tough-cookie-filestore")
const cookieJar = new tough.CookieJar(new FileCookieStore("./cookie.json"));


const cookieString = 等下结果填这里
const cookieList = cookieString.split('; ')
for (i in cookieList){
  cookieJar.setCookieSync(cookieList[i], 'http://picupload.service.weibo.com');
}
```

然后手动登录微博,打开 `http://weibo.com/minipublish` 打开控制台,得到cookie(亲测documen.cookie不行)
![image](https://user-images.githubusercontent.com/10610925/32206240-ffc23b26-bdc1-11e7-8f3f-d31dcc682b5a.png)

把cookie的值复制到上面那个文件,清空cookie.json内容,运行后就行了

**Comment by J3n5en** [comment]
至于验证码的问题可能要等我空闲下来才能解决....

**Comment by J3n5en** [comment]
@shirakun 嘤嘤嘤,刚刚翻了下你github,没想到是你,之前用过你的ssl证书...感谢

**Comment by shirakun** [comment]
好了,顺便我ssl相关的代码都在自己的gitlab里,你是如何通过github知道我的?

**Comment by J3n5en** [comment]
@shirakun 看到你的联系方式(email)感觉很眼熟,和那个ssl网址一致.......
